import http from 'node:http';
const port = Number(process.env.CDP_PORT || 9394);
const getJSON = (p) => new Promise((res, rej) => { http.get({host:'127.0.0.1',port,path:p}, r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>res(JSON.parse(b)));}).on('error',rej); });
const targets = await getJSON('/json/list');
const page = targets.find(t => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id=0; const pending=new Map();
const send=(m,p={})=>new Promise(res=>{const k=++id;pending.set(k,res);ws.send(JSON.stringify({id:k,method:m,params:p}));});
ws.onmessage=ev=>{const m=JSON.parse(ev.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}};
await new Promise(r=>{ws.onopen=r;});
await send('Page.enable');
await send('Page.reload', { ignoreCache: true });
console.log('hard reload done');
process.exit(0);